
online: false

logging.config: classpath:log-dev.xml

server.port: 8989

spring.application.name: task

register.center: http://127.0.0.1:6060/eureka/
eureka:
  client:
    healthcheck.enabled: true
    registry-fetch-interval-seconds: 10
    serviceUrl.defaultZone: ${register.center}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
