
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/common?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.github.common.sql.ShowSqlInterceptor
  username: root
  password: root
  hikari:
    minimumIdle: 1
    maximumPoolSize: 1

# 连接池数量见: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
