
spring:
#  session:
#    store-type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
  http.multipart:
    maxFileSize: 12Mb
    maxRequestSize: 20Mb

# 让 FeignClient 的断路器生效
# feign.hystrix.enabled: true

#zuul:
#  ignored-services: web-manager
#  routes:
#    common:
#      path: /common/**
#      serviceId: common
#      stripPrefix: false
#    user:
#      path: /user/**
#      serviceId: user
#      stripPrefix: false
#    product:
#      path: /product/**
#      serviceId: product
#      stripPrefix: false
#    trade:
#      path: /trade/**
#      serviceId: trade
#      stripPrefix: false
