
online: true

server.port: 8092

spring.application.name: product

logging.config: classpath:log-prod.xml

spring.datasource:
  url: jdbc:mysql://prod_product_db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
  username: prod_product_user
  password: prod_product_pass
  hikari:
    minimumIdle: 10
    maximumPoolSize: 30
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true

register.center: http://prod1:8761/eureka/,http://prod2:8761/eureka/,http://prod3:8761/eureka/
eureka:
  client:
    healthcheck.enabled: true
    registry-fetch-interval-seconds: 5
    serviceUrl.defaultZone: ${register.center}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
