
online: true

logging.config: classpath:log-dev.xml

server.port: 8787

spring.application.name: web

register.center: http://prod1:6060/eureka/,http://prod2:6060/eureka/,http://prod3:6060/eureka/
eureka:
  client:
    healthcheck.enabled: true
    registry-fetch-interval-seconds: 10
    serviceUrl.defaultZone: ${register.center}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

feign.hystrix.enabled: true
